apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=          # echo -n "postgres" | base64
  POSTGRES_PASSWORD: cG9zdGdyZXM=      # echo -n "postgres" | base64
  POSTGRES_DB: cG9zdGdyZXMtZGI=        # echo -n "postgres-db" | base64