apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "postgres-db"
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  CONNECTION_STRING: "Host=postgres-service;Port=5432;Database=postgres-db;Username=postgres;Password=postgres"