apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-service
  namespace: default
spec:
  selector:
    app: dotnet-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
  type: NodePort